### ISSUE TITLE
Update errors from backend on dogs, matches and users routes

### ISSUE THREAD

**Issue by jae-finger** [nerd-out/sniffr-fe#113]
I updated error codes and messages in the backend. Updated messages include:

- [x] /login
- return make_response('Invalid login', 400)
- return make_response('Email or password missing', 400)
------
- [x] /register
- return make_response('Email already exists in database', 400)
------
- [ ] /dog/:id
- return make_response("Dog not found", 400)
------
- [ ] /dog post
- return make_response("Dogs are limited to 3 activities", 400)
- return make_response("Dog not found", 400)
- successful edit = make_response(jsonify(edit_response), 200)
------
- [ ] /dog delete
- return make_response("Dog not found", 400)
------
- [x] /matches
- returns empty list if no matches

**Comment by allie-rae** [comment]
- Login errors are working
- Matches errors are working 

Register and dog settings are still under construction. 👍
